export * from './HomePage'
export * from './LayoutPage'
export * from './AboutPage'
export * from './BlogPage'
export * from './PorfolioPage'
export * from './PublicationsPage'
export * from './NotFoundPage'